/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"
#include "foo.i"

std::string sample_publish_other_includes_extensions::Greeter::greeting() {
    return std::string("Hello, World!");
}

int main () {
    sample_publish_other_includes_extensions::Greeter greeter;
    std::cout << greeter.greeting() << " -- " << kFoo << std::endl;
    return 0;
}
